### ISSUE TITLE
BwtB deletes needed runfiles from output base

### ISSUE THREAD

**Issue by JaredNeil** [bazelbuild/bazel#12635]
### Description of the problem:

With `--remote_download_toplevel`, runfiles are not downloaded even if they are missing from the output base under certain circumstances.
If a target that is used as `data` in a `bazel test` is cached, it will be downloaded for the test, but then [deleted right afterward](https://github.com/bazelbuild/bazel/blob/9b9bda625bd39f8853c99261bb7924c815d00161/src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java#L788-L810).
Then, if you `bazel run` something that also uses that cached target as `data`, the bazel server will think the file already exists in the output base, and won't download it. This leads to broken symlinks in the binary's runfiles tree.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Steps to reproduce:
https://gist.github.com/JaredNeil/aaba7e65e22c0a064251f2c2f4e6c6b8
Download zip and run `bash -x repro.sh`.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

```
release 3.7.1
```

### Any other information, logs, or outputs that you want to share?

Full output of running `repro.sh` from the gist linked above:
```
$ bash -x repro.sh
+ chmod +x test.sh publish.sh
+ bazelisk build //:data
Starting local Bazel server and connecting to it...
INFO: Invocation ID: dccc83b8-10b1-4651-b4f6-3ad19c2d1902
INFO: Analyzed target //:data (5 packages loaded, 7 targets configured).
INFO: Found 1 target...
Target //:data up-to-date:
  bazel-bin/data.txt
INFO: Elapsed time: 1.617s, Critical Path: 0.08s
INFO: 2 processes: 1 internal, 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
+ bazelisk clean
INFO: Invocation ID: 185a7ec5-29ed-45fb-a5c3-3bd9d7fe7cad
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
+ bazelisk test //:test
INFO: Invocation ID: 3c3b3346-d8d3-46e2-988c-ab64e12c1e5e
INFO: Analyzed target //:test (22 packages loaded, 229 targets configured).
INFO: Found 1 test target...
Target //:test up-to-date:
  bazel-bin/test
INFO: Elapsed time: 4.144s, Critical Path: 0.11s
INFO: 6 processes: 1 remote cache hit, 3 internal, 2 linux-sandbox.
INFO: Build completed successfully, 6 total actions
//:test                                                                  PASSED in 0.0s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 6 total actions
+ bazelisk run //:publish
INFO: Invocation ID: d87693e1-3cca-4087-beca-63a9290c93db
INFO: Analyzed target //:publish (0 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //:publish up-to-date:
  bazel-bin/publish
INFO: Elapsed time: 0.160s, Critical Path: 0.01s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
lrwxrwxrwx 1 jaredneil jaredneil 132 Dec  4 21:43 data.txt -> /home/jaredneil/.cache/bazel/_bazel_jaredneil/e78557b1a5d5d19319bf331b359d3c1d/execroot/__main__/bazel-out/k8-fastbuild/bin/data.txt
Symlink is broken because the target file doesn't exist in the output base
+ echo 'Pubish exit code: 1'
Pubish exit code: 1
```

**Comment by coeuvre** [comment]
The error is not caused by the deletion of the intermediate outputs. Looking at the steps of your repro case:
  1. Build `//:data` remotely to populate the remote cache.
  2. Clean the local workspace and remove `data.txt`.
  3. Test `//:test` remotely. Bazel **won't** download `data.txt` since the test is executed remotely.
  4. Run `//:publish` but failed since `data.txt` is not available locally.

The root cause is that Bazel never get a change to download `data.txt` in this case as downloads from remote cache only happens inside SpawnAction execution and `sh_binary` is not implemented as SpawnAction.

I am working on separation of downloads which will fix this issue.

**Comment by JaredNeil** [comment]
>3. Test //:test remotely. Bazel won't download data.txt since the test is executed remotely.

How is the test executed remotely?
Still fails if you add `tags = ["no-remote", "local"],` to `//:test`.
It succeeds if you don't run the `bazelisk test //:test` between the `clean` and `run`.
Also succeeds if you `shutdown` between the `test` and `run`.
So the `test` command is doing something to Bazel's internal state that breaks the `run` command.

**Comment by coeuvre** [comment]
> How is the test executed remotely?

Test command is implemented as SpawnAction which is not that different from other build actions so it can be executed remotely.

> Still fails if you add tags = ["no-remote", "local"], to //:test.

In this case, `//:test` is executed locally and `data.txt` is downloaded before the test execution. The reason for the failure is as you expected that `data.txt` is then deleted right afterward.

> It succeeds if you don't run the bazelisk test //:test between the clean and run.

This is another story if you look into the steps:

  1. Build `//:data` remotely to populate the remote cache.
  2. Clean the local workspace and remove `data.txt`.
  3. Run `//:publish` which need to build `//:publish` first:
     1. Calculate top level files to download since we are in `--remote_download_toplevel` mode. The set of files to download include `data.txt`.
     2. Build dependencies for `//:publish` first if not already built. In this case Bazel will build `//:data` since we just cleaned the workspace.
     3. `//:data` is `genrule` which is implemented as SpawnAction. Bazel will run it remotely and find that it's output `data.txt` is included in the set of files to download, hence download `data.txt`.
   4. Since `data.txt` is downloaded during the execution of `//:data`, running of `//:publish` will be succeeded.

The difference is that `data.txt` is not included in the set of files to downloaded for `bazel test //:test`. So Bazel won't download `data.txt` in that case. And if you build `//:publish` right after `//:test`, `data.txt` won't be downloaded since there is no SpawnAction executed.

> Also succeeds if you shutdown between the test and run.

This is actually caused by a missing feature that metadata for the remote files don't get persisted across server restarts. (It's kind of weird that a missing feature leads to a succeeded build)

  1. Shutdown the server, Bazel losts the knowledge about remote files.
  2. Run `//:publish`, Bazel will start the server and start to build `//:publish`. 
  3. Since Bazel can't find `data.txt` both on the disk and on its internal metadata store, it will build `//:data` again.
      - Bazel will find out that the action was executed before and use the cached result in the remote server
  4. The remaining steps are the same to the case above which you don't run `test` between `clean` and `run`.

Sorry for confusing you but we do have rooms for improvement here and I am constantly working on them.

**Comment by coeuvre** [comment]
> In this case, //:test is executed locally and data.txt is downloaded before the test execution. The reason for the failure is as you expected that data.txt is then deleted right afterward.

This is fixed by f0c32de0823307ec293a882af6a9c7a48631d33b.

**Comment by JaredNeil** [comment]
https://github.com/bazelbuild/bazel/commit/f0c32de0823307ec293a882af6a9c7a48631d33b does seem to fix the issue in some cases. The publish step still fails if the test is cached completely. I've updated the repro gist to run the test before the clean instead of just building the data.

**Comment by coeuvre** [comment]
With recent developments on BwoB, I believe this issue is fixed. I also verified with the repro you provided and it worked. Closing. Feel free to reopen if it doesn't work for you.

**Comment by JaredNeil** [comment]
Thank you for the update! Confirmed it still fails on `5.3.2` and `6.0.0-pre.20221020.1`, but passes on `7.0.0-pre.20221026.2` and `last_green`.

**Comment by brentleyjones** [comment]
How about 6.0rc1? Just checking if we need to cherry-pick anything into the release.

**Comment by JaredNeil** [comment]
Repro also passes on `6.0.0rc1`, so I don't think we need a cherry-pick to make the `6.0.0` release.
