### ISSUE TITLE
 Remove -Xverify:none from Java invocations

### ISSUE THREAD

**Issue by doompadee** [bazelbuild/bazel#13097]
When compiling with the Java 15 toolchain under Bazel 4.0.0, I receive an annoying warning about a deprecated `verify:none` option. #11773 addressed a similar issue for the Java 14 toolchain. Please consider removing.

Repro for Linux here: https://github.com/doompadee/noverify

```
$ bazel build //...
INFO: Analyzed 2 targets (23 packages loaded, 746 targets configured).
INFO: Found 2 targets...
INFO: From Compiling Java headers src/main/java/foo/libfoo-hjar.jar (1 source file):
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
INFO: Elapsed time: 4.424s, Critical Path: 3.92s
INFO: 6 processes: 1 internal, 3 linux-sandbox, 2 worker.
INFO: Build completed successfully, 6 total actions
```

**Comment by davido** [comment]
It's a known issue, see this attempt to remove it: https://github.com/bazelbuild/bazel/pull/11774.

//CC @meisterT, @cushon.

**Comment by doompadee** [comment]
Oh, I only had a cursory look and thought this issue has been fixed for Java 14 and resurfaced with 15...

If startup performance matters that much for the server, maybe keep the option there but remove it from the JavaHeaderCompileActionBuilder?

**Comment by meisterT** [comment]
cc @comius

**Comment by comius** [comment]
I thought this was already fixed, issues #11773 probably should have been closed.

Since this is related to JDK>11, -Xverify:none should be move into toolchain definition for JDK11 and the hardcoded version should be removed from Bazel.

**Comment by davido** [comment]
> I thought this was already fixed [...]

Unfortunately it wasn't fixed yet. if you try to build with java 15, the build logs are spammed with these warnings.

**Comment by cushon** [comment]
https://github.com/bazelbuild/bazel/issues/11381 was a related change to Java tools, but the startup option still exists.

I'm not sure we want to upgrade the embedded JDK to 17 without fixing this: https://github.com/bazelbuild/bazel/pull/16541

@meisterT would you be willing to revisit the benchmarking from https://github.com/bazelbuild/bazel/pull/11774#issuecomment-660182407 with JDK 17? I remember some discussion that CDS might help offset the cost of losing `-Xverify:none`, but maybe not completely.

**Comment by meisterT** [comment]
I redid benchmarking and added results here: https://github.com/bazelbuild/bazel/pull/11774#issuecomment-1318848456
