### ISSUE TITLE
Failing to run d8_dexbuilder with buildtools 31

### ISSUE THREAD

**Issue by Kernald** [bazelbuild/bazel#13989]
### Description of the problem / feature request:

Using buildtools 31, Bazel can't build dex files anymore. With d8 disabled (default):
```
ERROR: /private/var/tmp/_bazel_kernald/dc8fa02be43b6315d36f6bf2bf056429/external/androidsdk/BUILD.bazel:13:25: Extracting interface @androidsdk//:dx_jar_import failed: missing input file 'external/androidsdk/build-tools/31.0.0/lib/dx.jar', owner: '@androidsdk//:build-tools/31.0.0/lib/dx.jar'
ERROR: /private/var/tmp/_bazel_kernald/dc8fa02be43b6315d36f6bf2bf056429/external/androidsdk/BUILD.bazel:13:25 Extracting interface @androidsdk//:dx_jar_import failed: 1 input file(s) do not exist
```

With d8 enabled with the following flags:
```
# Enable d8 merger
build --define=android_dexmerger_tool=d8_dexmerger

# Flags for the d8 dexer
build --define=android_incremental_dexing_tool=d8_dexbuilder
build --define=android_standalone_dexing_tool=d8_compat_dx
build --nouse_workers_with_dexbuilder
```

```
ERROR: /private/var/tmp/_bazel_kernald/dc8fa02be43b6315d36f6bf2bf056429/external/maven/BUILD:4748:11: Dexing external/maven/_dx/androidx_transition_transition/classes_and_libs_merged.jar_desugared.jar with applicable dexopts [] failed: (Exit 1): d8_dexbuilder failed: error executing command bazel-out/darwin-py2-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/android/d8_dexbuilder ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Error: Could not find or load main class com.android.tools.r8.compatdexbuilder.CompatDexBuilder
Caused by: java.lang.ClassNotFoundException: com.android.tools.r8.compatdexbuilder.CompatDexBuilder
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In a `WORKSPACE`:
```
android_sdk_repository(
    name = "androidsdk",
    api_level = 31,
    build_tools_version = "31.0.0",
)
```

(I don't think the `api_level` actually matters here.)

Try to build anything that requires dexing.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 4.2.1

**Comment by c16a** [comment]
I'm having the same issue. Any clues what might have gone wrong?

**Comment by ahumesky** [comment]
With build tools 31, dx has been removed, and the latest version of d8 moved some classes around. I think his should fix it:
https://github.com/bazelbuild/bazel/commit/ceb498fd6b9323a738f0ba628d12a23a161a0671
Can you try again with the latest bazel release? Looks like this is in 5.0 and 6.0

**Comment by nkoroste** [comment]
Tried with both Bazel 5 and 6 and it's still an issue (Also tried cherry-picking that PR into Bazel 4.2.2)

Here is how I setup d8. Without it it complains about `dx` missing which is expected. 
```
# Enable D8 instead of DexBuilder and DexMerger
build --config=d8
build:d8 --define=android_dexmerger_tool=d8_dexmerger
build:d8 --define=android_incremental_dexing_tool=d8_dexbuilder
build:d8 --nouse_workers_with_dexbuilder # https://github.com/bazelbuild/bazel/issues/10241
build:d8 --incremental_dexing # to overwrite our default
```

```
android_sdk_repository(
    name = "androidsdk",
    api_level = 31,
    build_tools_version = "31.0.0",
)
```

**Comment by alyssawilk** [comment]
Is there any advice of what to do without bumping bazel?  We've just started having the same problem recently but haven't changed android_sdk_repository or our bazel version so I'm not sure why something broke?

**Comment by nkoroste** [comment]
I've managed to cherry-pick https://github.com/bazelbuild/bazel/commit/ceb498fd6b9323a738f0ba628d12a23a161a0671 into 4.2.2 pretty easily and it seemed to solve the problem when `build_tools_version = "31.0.0",` is used with `d8`

**Comment by alyssawilk** [comment]
Ah if anyone else ends up in our situation (where updating bazel isn't trivial) explicitly hard-coding build_tools_version to a lower version worked for us
-android_sdk_repository(name = "androidsdk", api_level = 30)
+android_sdk_repository(name = "androidsdk", api_level = 30, build_tools_version = "30.0.2")

**Comment by nkoroste** [comment]
@ahumesky @sgjesse 

Good news, https://github.com/bazelbuild/bazel/commit/ceb498fd6b9323a738f0ba628d12a23a161a0671 fixes the issue that allows you to use `build_tools_version = "31.0.0",` 

Bad news, the above change introduces some new issues with d8/r8 where Bazel DexMerger is falling back to Platform SDK's D8. This is causing a crash with too many methods being fit into a singular DEX. 
```
Error: Cannot fit requested classes in a single dex file (# methods: 890463 > 65536 ; # fields: 468383 > 65536). Try supplying a main-dex list
```
The root cause is that D8 is being invoked with the default `min-api` value of `1`, which forces single DEX. 

It appears we should pass through `—min-api` to avoid this problem.

**Comment by Kernald** [comment]
> @ahumesky @sgjesse
> 
> Good news, [ceb498f](https://github.com/bazelbuild/bazel/commit/ceb498fd6b9323a738f0ba628d12a23a161a0671) fixes the issue that allows you to use `build_tools_version = "31.0.0",`
> 
> Bad news, the above change introduces some new issues with d8/r8 where Bazel DexMerger is falling back to Platform SDK's D8. This is causing a crash with too many methods being fit into a singular DEX.
> 
> ```
> Error: Cannot fit requested classes in a single dex file (# methods: 890463 > 65536 ; # fields: 468383 > 65536). Try supplying a main-dex list
> ```
> 
> The root cause is that D8 is being invoked with the default `min-api` value of `1`, which forces single DEX.
> 
> It appears we should pass through `—min-api` to avoid this problem.

Another work-around is to manually passing a number of `dex_shards` to every `android_binary`. It's simple enough to compute, just a bit annoying.

**Comment by EdbertChan** [comment]
@Kernald How were you able to even get this to run?

I'm getting `Error: Could not find or load main class com.android.tools.r8.compatdx.CompatDx`. If you peek inside the packaged d8.jar file that is in build_tools 31.0.0, CompatDx doesn't even exist as a class. I can confirm this exists in 29.0.0 in the d8.jar. but not 31.0.0.

In fact, if you look at the R8 source, [CompatDx](https://r8.googlesource.com/r8/+/refs/heads/main/src/main/java/com/android/tools/r8) got removed entirely. Maybe I should file this as an entirely separate issue.

**Comment by sgjesse** [comment]
`CompatDx` was moved from R8 to bazel [`com.google.devtools.build.android.r8.CompatDx`](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/tools/android/java/com/google/devtools/build/android/r8/CompatDx.java). It was [removed from R8](https://r8.googlesource.com/r8/+/ea7348e94b745c309a3b1606784d5c90be92c330) almost two years ago.

**Comment by EdbertChan** [comment]
@ahumesky We are running 5.1.0. We have forked it but we only have a few small diffs ontop of it mostly related to manifest merging. I am using the same configs that Kernald is using.

The error I get from --verbose_failures boils down to this line
bazel-out/k8-opt-exec-2B5CBBC6/bin/external/androidsdk/d8_compat_dx --dex '--num-threads=5' '--output=bazel-out/k8-fastbuild/bin/apps/presidio/helix/app-apk/_mobile_install/bin_debug/stub_application/classes.dex' bazel-out/k8-fastbuild/bin/apps/presidio/helix/app-apk/_mobile_install/bin_debug/stub_deploy.jar

When I look into the d8_compat_dx, I only see that a manifest file exists in it where it says it was created by "Target-Label: @androidsdk//:d8_compat_dx" and no other classes. Looking at this line in [android_sdk_repository.bzl,](https://github.com/bazelbuild/bazel/blob/66d07f096cb697bdadb6f9d9fbc1c4fe33be6d59/tools/android/android_sdk_repository_template.bzl#L306) it looks like Bazel is still trying to use the d8 packaged in build-tools in the Android SDK rather than trying to create its own.

**Comment by ahumesky** [comment]
Gotcha yeah, I see now it's CompatDx vs CompatDexBuilder. We have some changes we'll push out later today that should address this

**Comment by nkoroste** [comment]
What version of Bazel did this fix end up landing in?

**Comment by ahumesky** [comment]
Right, because of the rollbacks and rollback of rollbacks it's a bit unclear, the final commit is https://github.com/bazelbuild/bazel/commit/ae247145b897d0f41cdf2b317f5c7b856845e303
and as of right now that's in the recent rolling releases:

[6.0.0-pre.20220608.2](https://github.com/bazelbuild/bazel/releases/tag/6.0.0-pre.20220608.2)
[6.0.0-pre.20220601.1](https://github.com/bazelbuild/bazel/releases/tag/6.0.0-pre.20220601.1)
[6.0.0-pre.20220526.1](https://github.com/bazelbuild/bazel/releases/tag/6.0.0-pre.20220526.1)
[6.0.0-pre.20220520.1](https://github.com/bazelbuild/bazel/releases/tag/6.0.0-pre.20220520.1)
[6.0.0-pre.20220517.1](https://github.com/bazelbuild/bazel/releases/tag/6.0.0-pre.20220517.1)
