### ISSUE TITLE
problems when building bazel on mips64

### ISSUE THREAD

**Issue by Mabelian** [bazelbuild/bazel#14097]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
I downloaded bazel-pre-5.0.0-dist.zip and tried to build bazel on mips64 architecture. I builted with jdk 8 and jdk 11, the same bug happened.

ERROR: /tmp/bazel_twgOGtF0/out/external/bazel_tools/tools/jdk/BUILD:29:19: While resolving toolchains for target @bazel_tools//tools/jdk:current_java_runtime: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: 

how to fix this bug?

**Comment by PiotrSikora** [comment]
FWIW, I have the same problem trying to bootstrap 5.0.0rc3 on RISC-V 64:
```sh
$ BAZEL_JAVAC_OPTS="-J-Xms2048m -J-Xmx4096m" EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
Building Bazel from scratch......
Building Bazel with Bazel.
WARNING: Option 'java_toolchain' is deprecated
WARNING: Option 'host_java_toolchain' is deprecated
WARNING: Option 'host_javabase' is deprecated
ERROR: /tmp/bazel_uYs2cPdH/out/external/bazel_tools/tools/jdk/BUILD:29:19: While resolving toolchains for target @bazel_tools//tools/jdk:current_java_runtime: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted:
INFO: Elapsed time: 929.304s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (362 packages loaded, 8838 targets configured)
ERROR: Could not build Bazel
```
Note that it succesfully builts itself from scratch (i.e. Java is working), so I suspect that there are some `selects` missing to cover bootstrapping from `mips64` and `riscv64` architectures that were added in https://github.com/bazelbuild/bazel/pull/13057.

**Comment by koenvervloesem** [comment]
I encountered the same error on ARMv7 (Raspbian GNU/Linux 10 on a Raspberry Pi 4).

**Comment by PiotrSikora** [comment]
@Wyverald is this a good candidate for 5.0.x or 5.1? Bootstrapping seems to be broken on at least 3 different platforms.

**Comment by Wyverald** [comment]
@bazel-io fork 5.1

**Comment by brentleyjones** [comment]
Any progress on fixing this before 5.1?

**Comment by ashione** [comment]
Any updates for this issue?
I got same error in 
```
ERROR: /github/home/.cache/bazel/_bazel_root/fa5a074cd6f1[25](https://github.com/ray-project/mobius/runs/5273958213?check_suite_focus=true#step:5:25)5c5f5cefe240bb7613/external/bazel_tools/src/conditions/BUILD:61:15: no such target '@platforms//cpu:riscv64': target 'riscv64' not declared in package 'cpu' defined by /github/home/.cache/bazel/_bazel_root/fa5a074cd6f1255c5f5cefe240bb7613/external/platforms/cpu/BUILD and referenced by '@bazel_tools//src/conditions:linux_riscv64'
INFO: Repository remote_coverage_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:3:13: in <toplevel>
Repository rule http_archive defined at:
  /github/home/.cache/bazel/_bazel_root/fa5a074cd6f1255c5f5cefe240bb7613/external/bazel_tools/tools/build_defs/repo/http.bzl:364:[31](https://github.com/ray-project/mobius/runs/5273958213?check_suite_focus=true#step:5:31): in <toplevel>
INFO: Repository com_google_absl instantiated at:
  /__w/mobius/mobius/streaming/WORKSPACE:16:15: in <toplevel>
  /github/home/.cache/bazel/_bazel_root/fa5a074cd6f1255c5f5cefe240bb7613/external/com_github_ray_project_ray/bazel/ray_deps_setup.bzl:217:22: in ray_deps_setup
  /github/home/.cache/bazel/_bazel_root/fa5a074cd6f1255c5f5cefe240bb7613/external/com_github_ray_project_ray/bazel/ray_deps_setup.bzl:76:24: in auto_http_archive
Repository rule http_archive defined at:
  /github/home/.cache/bazel/_bazel_root/fa5a074cd6f1255c5f5cefe240bb7613/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
ERROR: /github/home/.cache/bazel/_bazel_root/fa5a074cd6f1255c5f5cefe240bb7613/external/bazel_tools/tools/jdk/BUILD:90:11: errors encountered resolving select() keys for @bazel_tools//tools/jdk:jni
```

**Comment by comius** [comment]
The problem reported by @Mabelian and by @PiotrSikora is that Bazel doesn't resolve to local JDK by default (for tool) and the documentation is outdated.

I updated documentation to bootstrap using: `env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" ./compile.sh`
PR: https://github.com/bazelbuild/bazel/pull/15055/files

@Mabelian, @PiotrSikora, @koenvervloesem can try using this line? There might be follow up errors. I could break CPU detection and test it myself, but I wouldn't catch those.

---

The problem reported by @ashione:
You seem to be building something else than Bazel and the problem seems to be importing old version on @platforms repostiory. See https://github.com/bazelbuild/platforms and check commits that add riscv64 to CPU (like the error reported).

Bazel itself is using version 0.0.5, which has it: https://github.com/bazelbuild/platforms/blob/0.0.5/cpu/BUILD#L128-L131

**Comment by Wyverald** [comment]
@comius is this fixed by https://github.com/bazelbuild/bazel/pull/15055?

**Comment by comius** [comment]
> @comius is this fixed by #15055?

I think, but I'm not 100% sure, I'd prefer to wait for users verification.

**Comment by PiotrSikora** [comment]
I've tried to bootstrap `6.0.0-pre.20220310.1` with cherry-picked #15055, on both `mips64le` and `riscv64`.

On `mips64le`, the build still fails with the same message:
```
Building Bazel from scratch......
Building Bazel with Bazel.
ERROR: /tmp/bazel_xXOoVLIa/out/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'mips64'
ERROR: /tmp/bazel_xXOoVLIa/out/external/local_config_cc/BUILD:47:19: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Repository remote_java_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:247:6: in <toplevel>
  /tmp/bazel_xXOoVLIa/out/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /tmp/bazel_xXOoVLIa/out/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted:
INFO: Elapsed time: 472.713s
INFO: 0 processes.
```

On `riscv64`, the build eventually fails with `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space` (even with `--host_jvm_args=-Xmx2048m`, but maybe that doesn't work with `--tool_java_runtime_version=local_jdk`?).

In any case, the Bazel build (`Building Bazel with Bazel`) is started, so the reported issue seems to be fixed... Interestingly, it seems to be already fixed in `6.0.0-pre.20220310.1` (without #15055), so there is a different change that fixed it.

**Comment by PiotrSikora** [comment]
FWIW, I'm testing those under QEMU (using Docker multiarch), so you should be able to test this yourself:
```
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
```
```
$ docker run --rm -it --platform linux/mips64le debian:unstable
```
```
root@9d554f1b972d:/# uname -m
mips64
```
Note that it takes half a day for the `Building Bazel from scratch` step on those platfrorms under QEMU.

**Comment by ashione** [comment]
> The problem reported by @Mabelian and by @PiotrSikora is that Bazel doesn't resolve to local JDK by default (for tool) and the documentation is outdated.
> 
> I updated the documentation to bootstrap using:
> 
> ```
> env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" ./compile.sh
> ```
> 
> PR: https://github.com/bazelbuild/bazel/pull/15055/files
> 
> @Mabelian, @PiotrSikora, @koenvervloesem can try using this line? There might be follow up errors. I could break CPU detection and test it myself, but I wouldn't catch those.
> 
> The problem reported by @ashione: You seem to be building something else than Bazel and the problem seems to be importing old version on @platforms repostiory. See https://github.com/bazelbuild/platforms and check commits that add riscv64 to CPU (like the error reported).
> 
> Bazel itself is using version 0.0.5, which has it: https://github.com/bazelbuild/platforms/blob/0.0.5/cpu/BUILD#L128-L131

Did you mean its platform repo tool should be imported manually? I never update any @platforms old version in my projects. Or bazel release package might be modified to check out and make sure lastest platform plugin could be used.

**Comment by koenvervloesem** [comment]
> @Mabelian, @PiotrSikora, @koenvervloesem can try using this line? There might be follow up errors. I could break CPU detection and test it myself, but I wouldn't catch those.

I tried building Bazel 5.0 on ARMv7 (Raspbian GNU/Linux 10 on a Raspberry Pi 4) with `env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh` and got this now:

```
ERROR: /tmp/bazel_OkfTLxSr/out/external/com_google_protobuf/BUILD:470:10: Linking external/com_google_protobuf/protoc failed: (Exit 1): gcc failed: error executing command                                      
  (cd /tmp/bazel_OkfTLxSr/out/execroot/io_bazel && \                                                    
  exec env - \
    PATH=/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games \
    PWD=/proc/self/cwd \
  /usr/bin/gcc @bazel-out/arm-opt-exec-EDC14992/bin/external/com_google_protobuf/protoc-2.params)       
# Configuration: 362de6426bf439fe436db44fae9aad984ae1887cbb56188cc44665878362b809                       
# Execution platform: //:default_host_platform
bazel-out/arm-opt-exec-EDC14992/bin/external/com_google_protobuf/_objs/protobuf_lite/arena.o:arena.cc:function google::protobuf::internal::ArenaImpl::Init(): error: undefined reference to '__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 845.304s, Critical Path: 49.65s
INFO: 455 processes: 19 internal, 436 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
make: *** [Makefile:4: bazel] Error 1
```
