### ISSUE TITLE
jdks bloating the size of a default bazel sync

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#14511]
### Description of the problem / feature request:

bazel sync downloads a lot of JDKs. As more platform support gets added to https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE.tmpl the number of these that need to be downloaded increases, regardless of whether they are used in the project. Checking on a vaguely recent bazel version, we're up to 4.7Gb of JDKs.

Obviously this happens because jdk.WORKSPACE is injected regardless of whether projects asked for it. The on-demand downloading hides this from build commands, but sync can't do that.

The "natural" solution is to convert jdk.WORKSPACE into a macro that people load and call like any other builtin rules, but I understand how complicated that migration would be. Maybe something creative could be done to limit the default jdk.WORKSPACE injection to only be the current platform?

**Comment by keith** [comment]
This was likely fixed by https://github.com/bazelbuild/bazel/commit/903c2720792574321d3e3591ca14a9d287819cb7

Can you try HEAD?

**Comment by asuffield** [comment]
I can check, but that looks like it's fixing a different (related) issue. The sync command will download all repositories that are defined, regardless of whether they are used. That fix appears to be cleaning up an edge where too many are "used" and hence get downloaded by the build command.

**Comment by crt-31** [comment]
Can we keep this open?

Its still happening. We are using bazel sync to gather deps to an airgap network.  It syncs like 30 JDKs (total 5GB). Across all OSs, and several brands (i.e. microsoft, and openjdk and zulu), across several versions. (I only need the windows ones.) Using Bazel 7.5.0.

**Comment by fmeum** [comment]
Could you try using `bazel fetch` instead? `bazel sync` will go away with WORKSPACE and `bazel fetch` fetches just like `bazel build`.

**Comment by crt-31** [comment]
Can't use `bazel fetch` because our code can't go outside the airgap. What I am allowed to do is copy just the WORKSPACE file over that defines the external repos. But then I can only do a `bazel sync` because the `bazel fetch` will return mostly nothing cause there are no targets.

**Comment by fmeum** [comment]
@meteorcloudy for this special use case. `bazel vendor` may be able to do this for you.
