### ISSUE TITLE
Bazel build encyclopedia down

### ISSUE THREAD

**Issue by aaronmondal** [bazelbuild/bazel#18109]
### Page link:

https://bazel.build/reference/be/overview

### Problem description (include actual vs expected text, if applicable):

This subpage has been down for some time today.

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/reference/be/overview

### Any other information you'd like to share?

Noticed this ~1 hour ago. Initially thought this might resolve itself, but it seems that the page is still down at the time of writing this issue.

**Comment by aaronmondal** [comment]
2 hours later. Still down. @Wyverald maybe this is related to https://github.com/bazelbuild/bazel/commit/6dbac49ef52c1cb142779c2ef0e26a04170f6330?

**Comment by sgowroji** [comment]
Anove URL works fine, Could you please check again and update it. Thanks!

**Comment by aaronmondal** [comment]
@sgowroji Yep works again. Thanks.

Was actually down for a surprisingly long time. ~3 hours ago it was still down.

Closing since the issue is resolved.

**Comment by cbandera** [comment]
@sgowroji  I still can't acccess all pages. The above mentioned link works, but results from the search still point to wrong links. E.g.
https://bazel.build/rules/lib/CcInfo instead of the new location https://bazel.build/rules/lib/providers/CcInfo

Is this a local cache issue?

**Comment by cbandera** [comment]
I have cleaned by cache and I can neither use the help, nor the link from the original post. :(
Please reopen this issue.

**Comment by brentleyjones** [comment]
Correct, it 404s again now. Something is up.

**Comment by Wyverald** [comment]
The docs should be back online now (https://bazel.build/reference/be/overview and https://bazel.build/rules/lib). Keeping this open until we figure out what went wrong.

**Comment by fweikert** [comment]
There are two problems:
1. The docs pipeline deleted everything under /reference/be and /rules/lib -> we've restored the deleted pages manually and are working on a permanent fix of the pipeline
2. Most files under /rules/lib have been moved into subdirectories, but the site search is still showing the old results. We'll add more redirects and will check whether we can force the search to crawl the new pages.

**Comment by pauldraper** [comment]
> The docs should be back online now

They are not.

**Comment by trybka** [comment]
Context links into rules/lib also appear to be 404ing.

e.g. go to https://bazel.build/extending/rules#actions and click on `ctx.actions.declare_file` which goes to https://bazel.build/rules/lib/builtins/actions#declare_file and 404s.

**Comment by Wyverald** [comment]
The docs went offline overnight again. They're back online (again...) and we've made sure the fix has been deployed.

**Comment by fweikert** [comment]
Some context: A recent feature to remove stale documentation files contained a bug, which basically meant that the staging version of the pipeline went rampage and deleted all files. Both staging and prod binaries run once a day, so they basically ping-ponged between deleting and restoring the documentation.

**Comment by aaronmondal** [comment]
> Both staging and prod binaries run once a day, so they basically ping-ponged between deleting and restoring the documentation.

FWIW I find this hilarious and it soothes my pain of not being able to read Bazel docs for 2 days 🤣

Things seem to be working ATM. To make sure I'll wait ~24 hours and if everything continues working I'll close again.

**Comment by brentleyjones** [comment]
This still 404s (instead of redirect?): https://bazel.build/rules/lib/TemplateDict

**Comment by Wyverald** [comment]
We didn't set up redirects for every page that was moved, only the common ones. That's next on my to-do list.

**Comment by aaronmondal** [comment]
Seems like things have been working for a while now. Feel free to ping me if this becomes an issue again an I'll reopen.

**Comment by brentleyjones** [comment]
The link I posted above still 404s.

**Comment by Wyverald** [comment]
This should be fixed now thanks to @fweikert
