### ISSUE TITLE
android_integration_test broken on CI

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#1927]
Breakage: (for all HEAD on Ubuntu)
http://ci.bazel.io/job/bazel-tests/lastCompletedBuild/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=linux-x86_64/testReport/

Relative commit:
https://github.com/bazelbuild/bazel/commit/2fcf0e4cfb97af7cc8b8a090c5144c87b759bc13

If revert this change, the test passed on CI:
https://bazel-review.googlesource.com/#/c/6570/

**Comment by aj-michael** [comment]
Sorry, I just saw this now. I'm not quite sure what the problem is, but we should probably roll the CL back for now.

**Comment by aj-michael** [comment]
Instead of rolling this back, I have submitted a fix for the test. When ever the next time that internal code is committed to github, this test should be fixed.

**Comment by hermione521** [comment]
Sadly, it's not fixed.
http://ci.bazel.io/job/bazel-tests/280/

**Comment by aj-michael** [comment]
Hmmm, I cannot reproduce the failure locally. I tried:

```
$ git clone git@github.com:bazelbuild/bazel bazel-repro && cd bazel-repro
...
$ ./compile.sh
...
$ cp ~/WORKSPACE_WITH_SDK_NDK ./WORKSPACE
$ ./output/bazel test //src/test/shell/bazel/android:android_integration_test
...
INFO: Elapsed time: 75.831s, Critical Path: 71.62s
//src/test/shell/bazel/android:android_integration_test                  PASSED in 7.0s

Executed 1 out of 1 test: 1 test passes.
```

**Comment by aj-michael** [comment]
Hmm, I'm wondering if Bazel CI is caching the result of the `android_sdk_repository`?

**Comment by aj-michael** [comment]
I've created a rollback.

**Comment by hermione521** [comment]
Fixed. And CI is working perfectly now so feel free to test using gerrit.
