### ISSUE TITLE
ibtoolzip needs better output when run with -s or --verbose_failures

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#197]
Right now ibtoolzip doesn't actually show the invocation of ibtool when run with -s or --verbose_failures. 

/usr/bin/java -jar bazel-out/host/bin/tools/objc/ibtoolzip_deploy.jar bazel-out/local_darwin-fastbuild/bin/examples/objc/PrenotCalculator/examples/objc/PrenotCalculator/CalculatorViewController.nib.zip CalculatorViewController.nib /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --minimum-deployment-target 7.0 examples/objc/PrenotCalculator/CalculatorViewController.xib)

is the output, where I would expect to actually see the ibtool invocation.

**Comment by hanwen** [comment]
but that is the ibtool invocation, no?  It says 

 /usr/bin/java -jar bazel-out/host/bin/tools/objc/ibtoolzip_deploy.jar

that is an invocation of a program written in Java.

**Comment by dmaclach** [comment]
agreed, but someone looking at the output trying to debug what is wrong is actually going to want to see  what was passed to ibtool under the hood. Just because bazel is calling ibtoolzip_deploy as an intermediary step is a bazel implementation detail.

**Comment by damienmg** [comment]
bazel -s output the list of bazel command. ibtool is called through the ibtoolzip wrapper. I doubt there is anything more that can be done. Assigning to Daniel for confirming.

**Comment by Aragos** [comment]
The reason this doesn't print the command line is because of the ibtoolzip wrapper around the real ibtool. You can probably work out the commandline used by looking at https://github.com/google/bazel/blob/dfc9b62faa9e512df72bf8c8edca58e62d9d7160/src/tools/xcode-common/java/com/google/devtools/build/xcode/ibtoolzip/IbtoolZip.java#L54

Admittedly this isn't ideal but I also don't have a simple answer on how to fix this as (AFAIK) -s isn't propagated to the tool.

**Comment by hanwen** [comment]
Dave, I saw some changes passing by related to this. Is this fixed or still outstanding?

**Comment by hanwen** [comment]
wasn't this addressed in a56a58b7c63f32ffb7ec08b4d223d6e5bd14befc ?

**Comment by Aragos** [comment]
No, this isn't fixed yet but I'm working on it right now (passing the flags from blaze to the tools).

**Comment by damienmg** [comment]
Is it fixed? Can we close that bug? @Aragos ? @dmaclach ?

**Comment by hanwen** [comment]
closing due to inactivity.
