### ISSUE TITLE
[9.0.0] Bazel 8 hangs during build event upload

### ISSUE THREAD

**Issue by westrik** [bazelbuild/bazel#25232]
### Description of the bug:

I'm seeing an intermittent issue where a build will fail to exit after uploading build events. Seems like Bazel is waiting for background upload tasks even though they have all completed.

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This happens intermittently and I haven't found a straightforward repro.

### Which operating system are you running Bazel on?

Amazon Linux 2023.6.20250115

### What is the output of `bazel info release`?

release 8.0.1

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text

```

### Have you found anything relevant by searching the web?

Seems potentially related to https://github.com/bazelbuild/bazel/issues/21626 but I'm not using remote execution.

### Any other information, logs, or outputs that you want to share?

[jstack dump](https://github.com/user-attachments/files/18710658/jstack-l.txt)

**Comment by fmeum** [comment]
@tjgq @coeuvre We have reports from multiple users about these kinds of hangs. They seem to be caused by `--remote_cache_async`. In this particular case, it looks like the RemoteExecutionService is waiting on the `Phaser` even though no uploads are running anymore.

**Comment by fmeum** [comment]
@bazel-io fork 8.1.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.1.0 RC4](https://github.com/bazelbuild/bazel/releases/tag/8.1.0rc4). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.1.0rc4. Thanks!

**Comment by iancha1992** [comment]
@fmeum @westrik can you please check if [Bazel 8.1.0 RC4](https://github.com/bazelbuild/bazel/releases/tag/8.1.0rc4) fixes the issue? Thanks

**Comment by connyay** [comment]
We (@tanium) were seeing frequent hangs with 8.0.1. Hangs seem to be resolved with 8.1.0 rc4.

Thank you!

**Comment by iancha1992** [comment]
Fixed. See https://github.com/bazelbuild/bazel/issues/25232#issuecomment-2654835345

**Comment by westrik** [comment]
Unfortunately I'm still seeing this with 8.1.0rc4 (with `--remote_cache_async`). 

jstack dump: https://gist.github.com/westrik/9da3128bfac9d59ef781681b664d9267

**Comment by fmeum** [comment]
Possibly related: https://github.com/bazelbuild/bazel/issues/25308#issuecomment-2666767168

**Comment by iancha1992** [comment]
@bazel-io fork 8.2.0

**Comment by coeuvre** [comment]
It seems like the stack dump from https://github.com/bazelbuild/bazel/issues/25232#issuecomment-2669825861 is truncated and it's not clear why Bazel was waiting for the thread pool. Can you provide the complete stack dump next time it happens?

**Comment by westrik** [comment]
@coeuvre sorry, not sure how it got truncated. I've updated that gist with the full stack dump.

**Comment by leungster** [comment]
Here is a dump from my env when it hanged today.
[jvm.txt](https://github.com/user-attachments/files/19079787/jvm.txt)

**Comment by froody** [comment]
I am also seeing a hang after build, not sure if it's the same issue:

Java stacks: https://gist.github.com/froody/2ecc3acfdc2d3e194a94ea65ee3cf276
gdb stacks of server: https://gist.github.com/froody/cf8cfd5425caa09da502ec7a37255fe3
Strace: https://gist.github.com/froody/ac10b0a72719bc6f6b7b1030845c8310
Bazel build: https://github.com/tom-neara/bazel/tree/8.1.101

The bazel client is just stack waiting for grpc: https://gist.github.com/froody/b0a5a051fdf0a3b757b403cb8f724595

**Comment by fmeum** [comment]
Thanks @froody, your thread dump contains a stack trace that does seem to explain a deadlock when using an HTTP cache:
https://gist.github.com/froody/2ecc3acfdc2d3e194a94ea65ee3cf276#file-gistfile1-txt-L435-L525

Here, the `Channel` blocks on the closure of the `FixedChannelPool`, which in turn blocks on the closure of the `Channel` via https://gist.github.com/froody/2ecc3acfdc2d3e194a94ea65ee3cf276#file-gistfile1-txt-L554 (see
https://github.com/netty/netty/blob/58df783eb4fc50f95a1061dc4274020d6804caf4/transport/src/main/java/io/netty/channel/pool/SimpleChannelPool.java#L408).

**Comment by fmeum** [comment]
@coeuvre Given that we have the `backgroundTaskPhaser`, do we even need the `combinedCache` to be reference counted?

**Comment by froody** [comment]
@fmeum is there any quick-fix I could try?

**Comment by fmeum** [comment]
`--noremote_cache_async` is the only workaround I see at the moment.

**Comment by coeuvre** [comment]
@bazel-io fork 8.2.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.2.0 RC3](https://github.com/bazelbuild/bazel/releases/tag/8.2.0rc3). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.2.0rc3. Thanks!

**Comment by rkwon-retool** [comment]
@iancha1992, I'm a colleague of @westrik, I believe we're still seeing this despite having upgraded to `8.2.0rc3`

There's also possibly another issue we're seeing on this new release related to remote execution on buildkite?

```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/------/external/bazel_gazelle/pathtools/BUILD.bazel:3:11: GoCompilePkg external/bazel_gazelle/pathtools/pathtools.a failed: I/O exception during sandboxed execution: java.util.concurrent.ExecutionException: java.lang.InterruptedException
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/------/external/org_golang_x_mod/semver/BUILD.bazel:3:11: GoCompilePkg external/org_golang_x_mod/semver/semver.a failed: I/O exception during sandboxed execution: java.util.concurrent.ExecutionException: java.lang.InterruptedException
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData0{actionLookupKey=ConfiguredTargetKey{label=@@io_bazel_rules_go//:stdlib, config=BuildConfigurationKey[240063384f9257e894b5195f75fa38c16397f9c03ae72b3bb2698fbafd6e0bb9]}, actionIndex=0}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-opt-exec-ST-d57f47055a04/bin]external/io_bazel_rules_go/stdlib_/pkg')
```

**Comment by westrik** [comment]
> we're still seeing this despite having upgraded to 8.2.0rc3

here's another jstack dump: https://gist.github.com/westrik/442206ba091a57bfab54738a344d73ea

**Comment by fmeum** [comment]
@rkwon-retool Do you happen to have the full stack trace of the crash?

**Comment by westrik** [comment]
@fmeum here's a full stack trace: https://gist.github.com/westrik/b76ae32cec54df36ef8b5fe78cee2219

to be clear, that crash seems to be unrelated to the original issue where Bazel hangs while uploading build events, but the crashes did seem to start when we upgraded from 8.1.0rc4 to 8.2.0rc3

**Comment by fmeum** [comment]
@westrik Could you file an issue for this? That's code I added.

**Comment by westrik** [comment]
@fmeum filed https://github.com/bazelbuild/bazel/issues/25841

**Comment by coeuvre** [comment]
@rkwon-retool Do you happen to have the full stack trace for the hang?

**Comment by fmeum** [comment]
@coeuvre  I think that https://github.com/bazelbuild/bazel/issues/25232#issuecomment-2802626767 is meant to be that.

**Comment by coeuvre** [comment]
Oh right, I missed that.

**Comment by coeuvre** [comment]
@rkwon-retool it's not clear to me why it is hanging from the stack dump. Are the log files (`$OUTPUT_BASE/java.log`, `$OUTPUT_BASE/command.log` and `$OUTPUT_BASE/server/jvm.out`) still around?

**Comment by rkwon-retool** [comment]
Unfortunately not :(
The little container we have this running in is pretty ephemeral, and we didn't collect those artifacts at the time.

We have also unfortunately reverted this, since this was resulting in increased job failures for us. How critical is this for trying to resolve this issue do you think? I can try to repro by forcing the upgrade on an isolated set and then have them run through things until it repros

**Comment by rkwon-retool** [comment]
We might have data! I'll try to send it over before EOD if that's alright!

**Comment by rkwon-retool** [comment]
I then subsequently did not do it. Will try to take some time today.

**Comment by rkwon-retool** [comment]
TOMORROW. IT WILL DEFINITELY HAPPEN, AT THE TOP OF MY PRIORITY LIST.

**Comment by rkwon-retool** [comment]
Alright, I'm discovering that the hanging issue seems to be happening less often, but we're not actually surfacing those logs. Let me see if I can force them to appear and I'll upload them when they do

**Comment by rkwon-retool** [comment]
Hmm.

I think this maybe disappeared (or, at least, I can't easily find examples, where it was definitely **easier** before.)
We did upgrade to `8.2.1rc1`, where we were seeing this issue previously on `8.2.0rc3`

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/commit/76dfcc5fe9599d381f69943d3fa8fc4c064035ac didn't end up fixing this.

**Comment by fmeum** [comment]
A thread dump from a new run with the fix above contains these interesting threads:

```
remote-execution-bg-* (three in total) virtual
      java.base/java.lang.VirtualThread.park(Unknown Source)
      java.base/java.lang.System$1.parkVirtualThread(Unknown Source)
      java.base/java.util.concurrent.locks.LockSupport.park(Unknown Source)
      com.google.common.util.concurrent.AbstractFutureState.blockingGet(AbstractFutureState.java:244)
      com.google.common.util.concurrent.Platform.get(Platform.java:54)
      com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:253)
      com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:96)
      com.google.devtools.build.lib.remote.util.Utils.getFromFuture(Utils.java:114)
      com.google.devtools.build.lib.remote.util.Utils.waitForBulkTransfer(Utils.java:601)
      com.google.devtools.build.lib.remote.UploadManifest.upload(UploadManifest.java:611)
      com.google.devtools.build.lib.remote.RemoteExecutionService.doUploadOutputs(RemoteExecutionService.java:1898)
      com.google.devtools.build.lib.remote.RemoteExecutionService.lambda$uploadOutputs$8(RemoteExecutionService.java:1879)
      java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(Unknown Source)
      java.base/java.lang.VirtualThread.run(Unknown Source)

"grpc-default-boss-ELG-1-1"
      io.netty.channel.epoll.Native.epollWait(Native Method)
      io.netty.channel.epoll.Native.epollWait(Native.java:220)
      io.netty.channel.epoll.Native.epollWait(Native.java:213)
      io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:308)
      io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:365)
      io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
      io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
      io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
      java.base/java.lang.Thread.run(Unknown Source)

"grpc-default-worker-ELG-3-1" (three in total)
      io.netty.channel.epoll.Native.epollWait0(Native Method)
      io.netty.channel.epoll.Native.epollWait(Native.java:193)
      io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:304)
      io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:368)
      io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
      io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
      io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
      java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by fmeum** [comment]
Possibly related: https://github.com/grpc/grpc-java/issues/8334

**Comment by iancha1992** [comment]
@fmeum Should we put this on the release-9.0.0 blocker to ensure the fix is included in Bazel 9?

**Comment by fmeum** [comment]
@iancha1992 I have a lead now, so yes, please do that.

**Comment by fmeum** [comment]
We found that this reproduces less frequently with https://github.com/bazelbuild/bazel/blob/76dfcc5fe9599d381f69943d3fa8fc4c064035ac/src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java#L503 set to 50 and not at all with it set to 20.

**Comment by iancha1992** [comment]
Please note: The rc1 cut date has been rescheduled to Monday, November 3rd.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.5.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/8.5.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.5.0rc1. Thanks!
