### ISSUE TITLE
cc_library warning: file has no symbols

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#4057]
### Description of the problem / feature request / question:

On macOS, if a source file in a static `cc_library` doesn't define any global symbols, we see a warning like the one below:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/darwin_x86_64-fastbuild/bin/libempty.a(empty.o) has no symbols
```

This is a problem in rules_go. We use a tool in the Go toolchain (cgo) that generates some .c files that get compiled with `cc_library`. One of the generated files in each library frequently has no symbols, but it's hard to know ahead of time whether that's the case (the file is not empty).

It would be nice to suppress these warnings altogether. There may be a lot of libraries with cgo in a Go project, so our users may see a lot of warnings.

It looks like ranlib on macOS supports a flag `-no_warnings_for_no_symbols`. ar does not support this flag. The actual command that's emitting this warning looks like this: 

```
external/local_config_cc/wrapped_ar rcs bazel-out/darwin_x86_64-fastbuild/bin/libempty.a bazel-out/darwin_x86_64-fastbuild/bin/_objs/empty/empty.o
```

Maybe this flag can be added in [wrapped_ar.tpl](https://github.com/bazelbuild/bazel/blob/837e1b3d4859140d29aaa6bbab8fbb008e6d701e/tools/osx/crosstool/wrapped_ar.tpl)?

### If possible, provide a minimal example to reproduce the problem:

```
cc_library(
    name = "empty",
    srcs = ["empty.c"],
    linkstatic = 1,
)
```

empty.c is an empty file. Note that there are additional warnings if the entire library has no symbols. Those warnings don't affect rules_go, but they should probably be suppressed, too.

### Environment info
* Operating System: macOS Sierra 10.12.6

* Bazel version (output of `bazel info release`):  release 0.7.0

**Comment by robbertvanginkel** [comment]
Was this fixed with https://github.com/bazelbuild/bazel/issues/5981 / https://github.com/bazelbuild/bazel/commit/81b59f05cb0853d27055edf77e62b619ff0aa4ba ?

**Comment by cpsauer** [comment]
It looks to me like there's still an issue outstanding here somewhere. Not sure if it's a regression since #5981/https://github.com/bazelbuild/bazel/commit/81b59f05cb0853d27055edf77e62b619ff0aa4ba, or an edge case that's slipping through.

[I'm seeing this warning when building a .mm (Obj-C++) file using an objc_library.]

@tetromino, I'm hoping it's okay if I tag you, since you wrote the original fix--and I don't (quickly) see where thie invocation is slipping through without `-no_warning_for_no_symbols`. I can see that the flag has since been moved to //tool/osx/crosstool/cc_toolchain_config.bzl, I assume as part of the general migration to toolchains.

**Comment by cpsauer** [comment]
@keith, here's the repro, per [#5981](https://github.com/bazelbuild/bazel/issues/5981#issuecomment-1103315925):
[empty_warning.zip](https://github.com/bazelbuild/bazel/files/8517407/empty_warning.zip)
`bazel clean && bazel build :all`

Output should show the warning in all valid cases with {cc_library, objc_library}x{C, C++, Obj-C, and Objc-++}. 
That is, 6 instances of
`warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: bazel-out/applebin_macos-darwin_x86_64-fastbuild-ST-cfb676c6944e/bin/<whatever>.a the table of contents is empty (no object file members in the library define global symbols)`

**Comment by keith** [comment]
This warning is actually slightly different, and there doesn't appear to be a way to disable it:

https://github.com/keith/cctools/blob/bab7d4a19d480751ea4cba85d4c92b07991f2356/misc/libtool.c#L2915-L2925

**Comment by cpsauer** [comment]
Oy. I'm sorry, Keith, for feeding you a red herring. Shall we close this down, then, if we can't do better and the warning it referred to was fixed? I assume Apple wouldn't respond to feedback on something like this.

[I'd wrongly assumed that they'd just adjusted the error message, trusting a post I'd read online. Pretty cool that you've got that handy, searchable mirror of Apples open source tooling, though, and can just check the implementation.]

**Comment by keith** [comment]
This original issue can def be closed, but we could track that one separately, or not. Theoretically we could filter the output to just ignore that, IMO it's rarely going to indicate a real issue

**Comment by cpsauer** [comment]
Good call. Figured I'd PR it up while we were discussing. How about something like #15325?

**Comment by cpsauer** [comment]
(Have tested, and it fixes all the repro cases above and the instances in my own codebase that initially brought me to this issue.)
