### ISSUE TITLE
rules_docker fails to build  with bazel @ HEAD

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4206]
When I try to build `rules_docker` with `bazel` built @ HEAD, I get the following error:

```
ERROR: /home/elenairina/testnpe/rules_docker/testdata/BUILD:131:1: ImageLayer testdata/base_with_entrypoint-layer.tar failed (Exit 1)
Traceback (most recent call last):
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 23, in <module>
    from third_party.py import gflags
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/__init__.py", line 1, in <module>
    from gflags import *
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/gflags/__init__.py", line 871, in <module>
    _helpers.SPECIAL_FLAGS)
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/gflags/__init__.py", line 560, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/gflags/__init__.py", line 392, in DEFINE
    flag_values, module_name)
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/gflags/__init__.py", line 413, in DEFINE_flag
    fv[flag.name] = flag
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/gflags/flagvalues.py", line 442, in __setitem__
    raise exceptions.DuplicateFlagError.from_flag(name, self)
gflags.exceptions.DuplicateFlagError: The flag 'flagfile' is defined twice. First from third_party.py.gflags.gflags, Second from third_party.py.gflags.  Description from first occurrence: Insert flag definitions from the given file into the command line.
```

It seems the issue is in `bazel,` introduced by fb15f0f4e4885243d354a14997d09463594385bf. If I revert this commit and rebuild `bazel`, I can build `rules_docker` successfully.

This was discovered in #4173.

cc: @akira-baruah, author of commit

**Comment by mattmoor** [comment]
Hopefully this will either block 0.9?  @damienmg @dslomov

**Comment by jin** [comment]
Also breaking some Android integration tests: #4208

**Comment by akira-baruah** [comment]
Thanks for the heads up @iirina!

I was able to reproduce the bug and I'm testing a fix. I'll submit a PR once I confirm the fix locally.

**Comment by akira-baruah** [comment]
@iirina @jin #4212 should resolve these breakages.

**Comment by ulfjack** [comment]
Patch is merged and live. I missed the "fixes" lines from the commit description, which is why this wasn't auto-closed.

**Comment by dlorenc** [comment]
@ulfjack any idea how long this will take to get to ci.bazel.io? We're still seeing failures in rules_docker:

https://ci.bazel.io/blue/organizations/jenkins/PR%2Frules_docker/detail/rules_docker/293/pipeline

**Comment by tejal29** [comment]
@akira-baruah and @ulfjack we are still seeing failures. Any idea when this will be resolved?

**Comment by akira-baruah** [comment]
@tejal29 Where are you seeing these failures? The CI seems to be passing here:
