### ISSUE TITLE
CI BUILD_file_generator is failing with bazel 0.10.0 RC1

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4422]
BUILD_file_generator fails to build on Linux. The reported error is:

```
ERROR: /home/ci/workspace/Global/BUILD_file_generator-node=linux-x86_64/lang/scala/src/main/scala/com/google/devtools/build/bfg/scala/BUILD:16:1: in scala_library rule //lang/scala/src/main/scala/com/google/devtools/build/bfg/scala:scalapb_bfg_proto: 

Traceback (most recent call last):

	File "/home/ci/workspace/Global/BUILD_file_generator-node=linux-x86_64/lang/scala/src/main/scala/com/google/devtools/build/bfg/scala/BUILD", line 16

		scala_library(name = 'scalapb_bfg_proto')

	File "/home/ci/.cache/bazel/_bazel_ci/01c0940ac1a8a79ecff075b81c158a5c/external/io_bazel_rules_scala/scala/scala.bzl", line 704, in _scala_library_impl

		_lib(ctx, True)

	File "/home/ci/.cache/bazel/_bazel_ci/01c0940ac1a8a79ecff075b81c158a5c/external/io_bazel_rules_scala/scala/scala.bzl", line 634, in _lib

		_compile_or_empty(ctx, cjars, srcjars, non_macro_lib, <3 more arguments>)

	File "/home/ci/.cache/bazel/_bazel_ci/01c0940ac1a8a79ecff075b81c158a5c/external/io_bazel_rules_scala/scala/scala.bzl", line 354, in _compile_or_empty

		_compile(ctx, jars, srcjars, buildijar, <3 more arguments>)

	File "/home/ci/.cache/bazel/_bazel_ci/01c0940ac1a8a79ecff075b81c158a5c/external/io_bazel_rules_scala/scala/scala.bzl", line 278, in _compile

		try_to_compile_java_jar(ctx, scala_output, all_srcjars, java_s..., ...)

	File "/home/ci/.cache/bazel/_bazel_ci/01c0940ac1a8a79ecff075b81c158a5c/external/io_bazel_rules_scala/scala/scala.bzl", line 319, in try_to_compile_java_jar

		java_common.compile(ctx, source_jars = all_srcjars.to_...(), <8 more arguments>)

'host_javabase' must point to a Java runtime

ERROR: Analysis of target '//lang/scala/src/main/scala/com/google/devtools/build/bfg/scala:scalapb_bfg_proto' failed; build aborted: Analysis of target '//lang/scala/src/main/scala/com/google/devtools/build/bfg/scala:scalapb_bfg_proto' failed; build aborted

INFO: Elapsed time: 2.121s

FAILED: Build did NOT complete successfully (101 packages loaded)

FAILED: Build did NOT complete successfully (101 packages loaded)

script returned exit code 1
```

The console log can be found [here](https://ci.bazel.build/job/Global/job/BUILD_file_generator/157/console).
This is blocking the 0.10.0 release (#3958).

**Comment by iirina** [comment]
cc: @lberki can you investigate? It looks related to your recent javabase changes.

**Comment by iirina** [comment]
The same happens for rules_scala: [pipeline](https://ci.bazel.build/blue/organizations/jenkins/Global%2Frules_scala/detail/rules_scala/344/pipeline/)

**Comment by lberki** [comment]
Created https://github.com/bazelbuild/rules_scala/pull/384 . How do I test it?

**Comment by iirina** [comment]
Get the RC from [here](https://releases.bazel.build/0.10.0/rc1/index.html)) and try to build the scala tests:
`/path/to/bazel-0.10.0rc1 build //test/...`

**Comment by lberki** [comment]
`bazel test //test/...` goes further with this change in and bombs out with this error message:
```
ERROR: /usr/local/google/home/lberki/bazel/rules_scala/test/src/main/scala/scala/test/srcjars_with_java/BUILD:16:1: Compiling Java headers test/src/main/scala/scala/test/srcjars_with_java/java_source_jar_java-hjar.jar (1 files) failed (Exit 1)
Exception in thread "main" java.lang.IllegalArgumentException: unknown option: --
        at com.google.turbine.options.TurbineOptionsParser.parse(TurbineOptionsParser.java:165)
        at com.google.turbine.options.TurbineOptionsParser.parse(TurbineOptionsParser.java:53)
        at com.google.turbine.options.TurbineOptionsParser.parse(TurbineOptionsParser.java:41)
        at com.google.devtools.build.java.turbine.Turbine.compile(Turbine.java:46)
        at com.google.devtools.build.java.turbine.Turbine.main(Turbine.java:33)
Exception in thread "main" java.lang.IllegalArgumentException: unknown option: --
        at com.google.turbine.options.TurbineOptionsParser.parse(TurbineOptionsParser.java:165)
        at com.google.turbine.options.TurbineOptionsParser.parse(TurbineOptionsParser.java:53)
        at com.google.turbine.options.TurbineOptionsParser.parse(TurbineOptionsParser.java:41)
        at com.google.devtools.build.java.turbine.Turbine.compile(Turbine.java:46)
        at com.google.devtools.build.java.turbine.Turbine.main(Turbine.java:33
```

So I think it's a separate issue.

**Comment by lberki** [comment]
Indeed: that one is caused by https://github.com/bazelbuild/bazel/commit/baea3b16ab9ff1b9a1b7a758760d035ae096bfd5 . I haven't looked into how it's possible that Turbine in `@bazel_tools` doesn't support it.

**Comment by iirina** [comment]
Yup, that's a different issue. @cushon can you take a look?

@lberki Thanks for the PR.

**Comment by cushon** [comment]
I mailed a fix: cl/181475810

**Comment by cushon** [comment]
The issue with turbine and `--` is fixed, I'm not sure if there's anything else you want to leave this bug open to track.

**Comment by lberki** [comment]
I wanted to close this only when the Scala fix is merged, which I just did. So closing the bug.

**Comment by iirina** [comment]
Thank you both for the quick fixes!

**Comment by iirina** [comment]
BUILD_file_generator still failing with RC2 ([log](https://ci.bazel.build/blue/organizations/jenkins/Global%2FBUILD_file_generator/detail/BUILD_file_generator/168/pipeline/)).

The version of rules_scala must be updated in the [WORKSPACE](https://github.com/bazelbuild/BUILD_file_generator/blob/master/WORKSPACE) file.
