### ISSUE TITLE
Allow bazelrc to use Environment Variables.

### ISSUE THREAD

**Issue by tejal29** [bazelbuild/bazel#4635]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Right now, I could not find a  way to use environment variables in .bazelrc.
What i want to do is
```
$export GIT_ROOT=/workspace/project_name
and then in /workspace/project_name/.bazelrc
$cat /workspace/project_name/.bazelrc
build --action_env=GIT_ROOT="$GIT_ROOT"  # where $GIT_ROOT is the environment variable.
```

### Feature requests: what underlying problem are you trying to solve with this feature?
Pass on Environment variable to a bazel rule which runs a script.

### What operating system are you running Bazel on?
Linux and mac

### What's the output of `bazel info release`?
latest

###  Have you found anything relevant by searching the web?

Read, 
 - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
 - GitHub issues: https://github.com/bazelbuild/bazel/issues
 - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

**Comment by aehlig** [comment]
> Right now, I could not find a  way to use environment variables in .bazelrc.
> What i want to do is
> $export GIT_ROOT=/workspace/project_name
> and then in /workspace/project_name/.bazelrc
> $cat /workspace/project_name/.bazelrc
> build --action_env=GIT_ROOT="$GIT_ROOT" where $GIT_ROOT is the environment variable.

specifying --action_env with just the variable names tells bazel to inherit
that variable from the caller environment. So, adding

  build --action_evn=GIT_ROOT

to the respective rc-file and an exporting GIT_ROOT in your shell provides
the information to actions without the need of changing the syntax of rc-files.


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by philwo** [comment]
Seems like this is solved, closing. Please reopen if necessary.

**Comment by ittaiz** [comment]
Just to make sure- the general feature isn’t solved but the specific case,
right?

**Comment by philwo** [comment]
@ittaiz Yes, the case of "I want to have an environment variable available in the environment of my running actions" should be solved via `--action_env=MY_VAR`.

The case of "I want to use environment variables in my .bazelrc via string interpolation" like `build --jobs=$BAZEL_MAX_JOBS` is not solved, but it's not clear if we should even support it.

If you want / need that, I'd suggest to file a new FR for that :)
