### ISSUE TITLE
Binary installation without jdk not working

### ISSUE THREAD

**Issue by doompadee** [bazelbuild/bazel#4871]
Hello,

I'm having problems with the most recent Bazel releases when I use the binary installer option without an embedded OpenJDK.

Installation is done as outlined in the docs:

    chmod +x bazel-0.11.1-without-jdk-installer-linux-x86_64.sh
    ./bazel-0.11.1-without-jdk-installer-linux-x86_64.sh --user

For testing I try to build the Java example from the tutorial:

    git clone https://github.com/bazelbuild/examples.git
    cd examples
    bazel build //:ProjectRunner

This works fine with 0.9, but fails for both 0.10.1 and 0.11.1 with different error messages (see attached files below).

[output-0.11.1.txt](https://github.com/bazelbuild/bazel/files/1824734/output-0.11.1.txt)
[output-0.10.1.txt](https://github.com/bazelbuild/bazel/files/1824735/output-0.10.1.txt)

I'm running a Debian Jessie box with a custom Oracle JDK 1.8.0_162 installation below /opt (downloaded the .tar.gz from Oracle, unpacked and moved below /opt, set JAVA_HOME and configured `update-alternatives` for java and javac).

Please let me know if you need any further information. Any help would be appreciated. Thank you.

**Comment by philwo** [comment]
This is crashing inside `SkyframeExecutor.java`.
@janakdr @haxorz any idea?

@doompadee Can you reproduce this with Bazel 0.12.0rc1? (see https://releases.bazel.build/0.12.0/rc1/index.html)

**Comment by haxorz** [comment]
the crash in 0.10.1 was fixed by https://github.com/bazelbuild/bazel/commit/659974ed5e1fbd2122efc98ed7e1a0e3d5e59472.

the issue now manifests itself as an error message, as seen in output-0.11.1.txt.

ERROR: /home/doompadee/.cache/bazel/_bazel_doompadee/7eb93458c81b9689e868338db26168c0/external/bazel_tools/tools/jdk/BUILD:185:1: no such package '@local_jdk//': error globbing [bin/**] - [**/*%*/**]: /home/doompadee/.cache/bazel/_bazel_doompadee/7eb93458c81b9689e868338db26168c0/external/local_jdk/src/java (Permission denied) and referenced by '@bazel_tools//tools/jdk:host_jdk'

someone else on the bazel team would need to comment on whether this is WAI give what @local_jdk is trying to do.

**Comment by doompadee** [comment]
@philwo Still the same problem with 0.12.0rc

    doompadee@jessie:~/Dev/examples/java-tutorial$ bazel version
    Build label: 0.12.0rc1
    Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Sat Mar 24 03:42:37 +50170 (1521052227757)
    Build timestamp: 1521052227757
    Build timestamp as int: 1521052227757
    doompadee@jessie:~/Dev/examples/java-tutorial$ bazel build //:ProjectRunner
    ERROR: /home/doompadee/.cache/bazel/_bazel_doompadee/7eb93458c81b9689e868338db26168c0/external/bazel_tools/tools/jdk/BUILD:180:1: no such package '@local_jdk//': error globbing [bin/**] - [**/*%*/**]: /home/doompadee/.cache/bazel/_bazel_doompadee/7eb93458c81b9689e868338db26168c0/external/local_jdk/src/java (Permission denied) and referenced by '@bazel_tools//tools/jdk:jdk'
    ERROR: Analysis of target '//:ProjectRunner' failed; build aborted: Loading failed
    INFO: Elapsed time: 0.466s
    FAILED: Build did NOT complete successfully (1 packages loaded)

**Comment by doompadee** [comment]
Like the error message says, there is a permission problem. Using `sudo` makes things work, but that is not desirable.

**Comment by philwo** [comment]
How are the permissions set for your custom JDK in /opt? Can your user list all directories and read all files in there?

**Comment by doompadee** [comment]
That was it! The src folders did not have read permission for others. My apologies for the false alarm.

Thanks much for your kind help!
