### ISSUE TITLE
bazel uses invalid options when building with gcc on OS X

### ISSUE THREAD

**Issue by rnburn** [bazelbuild/bazel#5090]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

If you instruct bazel to build with gcc instead of clang on OSX, it uses incorrect options and fails.

### Feature requests: what underlying problem are you trying to solve with this feature?

Building with gcc on OSX.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Do the following:

```
<install gcc>
touch WORKSPACE
echo "int main() {return 0;}" > main.cpp
echo "cc_binary(name='t', srcs=['main.cpp'])" > BUILD
BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 bazel build -s --action_env CC=/usr/local/bin/g++-7 //...
```
this gives the error
```
Ryans-MacBook-Pro:bug ryanburn$ BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 bazel build -s --action_env CC=/usr/local/bin/g++-7 //...
INFO: Analysed target //:t (6 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //:t [action 'Compiling main.cpp']
(cd /private/var/tmp/_bazel_ryanburn/21d27257ba2b6523f4d7bef0fbb4c292/execroot/__main__ && \
  exec env - \
    CC=/usr/local/bin/g++-7 \
    PATH=/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/ryanburn/bin:/usr/local/opt/gettext/bin \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/darwin-fastbuild/bin/_objs/t/main.pic.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/_objs/t/main.pic.o' -fPIC -iquote . -iquote bazel-out/darwin-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/darwin-fastbuild/genfiles/external/bazel_tools -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c main.cpp -o bazel-out/darwin-fastbuild/bin/_objs/t/main.pic.o)
SUBCOMMAND: # //:t [action 'Creating runfiles tree bazel-out/darwin-fastbuild/bin/t.runfiles']
(cd /private/var/tmp/_bazel_ryanburn/21d27257ba2b6523f4d7bef0fbb4c292/execroot/__main__ && \
  exec env - \
    CC=/usr/local/bin/g++-7 \
    PATH=/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/ryanburn/bin:/usr/local/opt/gettext/bin \
  _bin/build-runfiles bazel-out/darwin-fastbuild/bin/t.runfiles_manifest bazel-out/darwin-fastbuild/bin/t.runfiles)
ERROR: /private/tmp/bug/BUILD:1:1: C++ compilation of rule '//:t' failed (Exit 1)
g++-7: error: unrecognized command line option '-Wthread-safety'; did you mean '-fthread-jumps'?
g++-7: error: unrecognized command line option '-Wself-assign'; did you mean '-Wcast-align'?
Target //:t failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.710s, Critical Path: 0.07s
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

OSX

### What's the output of `bazel info release`?

release 0.12.0-homebrew

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

https://stackoverflow.com/questions/47624689/how-to-set-c-compiler-on-os-x-with-bazel

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by benjaminp** [comment]
I recommend setting `CC` for the whole Bazel process like this: `CC=gcc bazel build //...`.

**Comment by mhlopko** [comment]
I'm afraid we have a bug in our [unix_cc_configure.bzl](https://source.bazel.build/bazel/+/master:tools/cpp/unix_cc_configure.bzl;l=275?q=unix_cc_configure). We add those flags unconditionally on darwin, which is wrong. Anybody want's to give it a try and fix it?

**Comment by rnburn** [comment]
I think there may be a few other places where clang-specific options are applied. I was able to compile a simple test after writing this wrapper script:
```python
#!/usr/bin/python

import os
import sys

drop_args = [
      "-Wthread-safety",
      "-Wself-assign",
      "-Wl,-no-as-needed",
      "-Wl,-z,relro,-z,now",
]

def main():
  compiler = "/usr/local/bin/g++-7"
  argv = []
  for arg in sys.argv[1:]:
      if not arg in drop_args:
          argv.append(arg)
  os.execv(compiler, [compiler] + argv)

if __name__ == "__main__":
  main()

```

**Comment by mhlopko** [comment]
I think there are 2 issues (I also observed them elsewhere):

1) `-Wthread-safety` and `-Wself-assign` are added unconditionally, and they should be instead guarded by `_add_option_if_supported`
2) `_add_option_if_supported` doesn't properly detect if `-Wl,-no-as-needed` and `-Wl,-z,relro,-z,now` are supported.

Would you mind verifying that my assumption about 2) is true? The command line is simple: https://source.bazel.build/bazel/+/master:tools/cpp/unix_cc_configure.bzl;l=156?q=_is_option_supported

**Comment by rnburn** [comment]
I think (2) is correct. I tried 
```bash
Ryans-MacBook-Pro:tmp ryanburn$ gcc-7 -Wl,-no-as-needed -c -o /dev/null empty.cc
Ryans-MacBook-Pro:tmp ryanburn$ echo $?
0
```
which isn't too surprising since it's checking a link option, but not linking.

**Comment by mhlopko** [comment]
Thanks Ryan, should be fixed now.

**Comment by vihanb** [comment]
I built 755278df00f65818dc092fe4f8a31bdec1aaaab5 from source, I still get the same error even when specifying gcc as CXX and CC:

```
bazel build --config=opt --config=cuda --action_env CXX=clang++ --action_env CC=clang --action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARY_PATH //tensorflow/tools/pip_package:build_pip_package
... build info...
ERROR: /private/var/tmp/_bazel_vihan/f108c5501e9eb04a78543225dfc48d61/external/fft2d/BUILD:21:1: C++ compilation of rule '@fft2d//:fft2d' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /private/var/tmp/_bazel_vihan/f108c5501e9eb04a78543225dfc48d61/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/Users/vihan/lib:/usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib: \
    PATH=/Users/vihan/lib:/usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib::/usr/local/opt/gpg-agent/bin:/usr/local/opt/findutils/libexec/gnubin:/opt/local/bin:/opt/local/sbin:/usr/local/texlive/2017/bin/x86_64-darwin:/Users/vihan/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/host/bin/external/fft2d/_objs/fft2d/external/fft2d/fft/fftsg.d -iquote external/fft2d -iquote bazel-out/host/genfiles/external/fft2d -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -g0 -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK '-march=native' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/fft2d/fft/fftsg.c -o bazel-out/host/bin/external/fft2d/_objs/fft2d/external/fft2d/fft/fftsg.o)
gcc: error: unrecognized command line option '-fcolor-diagnostics'
gcc: error: unrecognized command line option '-Wthread-safety'; did you mean '-fthread-jumps'?
gcc: error: unrecognized command line option '-Wself-assign'; did you mean '-Wcast-align'?
```

**Comment by mhlopko** [comment]
Isn't that the problem with the cuda toolchain that tensorflow provides? I see unconditional Wthread-safety in these files:
* https://github.com/tensorflow/tensorflow/blob/8a0ac6c1f9b1c29021bb725b2d20071264530602/third_party/gpus/crosstool/CROSSTOOL_nvcc.tpl
* https://github.com/tensorflow/tensorflow/blob/8a0ac6c1f9b1c29021bb725b2d20071264530602/third_party/toolchains/cpus/arm/CROSSTOOL.tpl
* https://github.com/tensorflow/tensorflow/blob/8753e2ebde6c58b56675cc19ab7ff83072824a62/third_party/toolchains/cpus/arm/CROSSTOOL.tpl

Can you report the issue in TF? You can reference fe63111 as a fix on our side, they'll want to do smth similar. Thanks!
