### ISSUE TITLE
Can't build Android samples

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#533]
I think I've followed the instructions, but I still get an error message trying to build the Android sample. I'm running commands from the root directory of the bazel repo. My WORKSPACE contains the following:

```
android_sdk_repository(
    name = "androidsdk",
    path = "/opt/android-sdk",
    # Available versions are under build-tools/.
    build_tools_version = "21.1.2",
    # Available versions are under platforms/.
    api_level = 20,
)

android_ndk_repository(
    name = "androidndk",
    path = "/opt/android-ndk",
    api_level = 20,  # Set this to the SDK's api_level.
)
```

When trying to build hello_world I get the following error:
```
# bazel clean
# bazel build //examples/android/java/bazel:hello_world
ERROR: /root/.cache/bazel/_bazel_root/aef1e07eca3d4d4bac211b6ac3bc513a/external/default_android_tools/src/tools/android/java/com/google/devtools/build/android/ziputils/BUILD:59:1: no such package '@default_android_tools//src/main/java/com/google/devtools/common/options': BUILD file not found on package path and referenced by '@default_android_tools//src/tools/android/java/com/google/devtools/build/android/ziputils:reducer'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.057s
```

This is running inside a Docker container based on Debian on an Ubuntu host machine.

**Comment by ahumesky** [comment]
The problem with the default_android_tools and the options package should
be fixed with the next push to bazel, however you can work around for now
by setting an android_local_tools_repository rule in your workspace file:

android_local_tools_repository(
    name = "android_tools",
    path = "/path/to/bazel",
)

**Comment by ekuefler** [comment]
Thanks, that resolved the default_tools error but the sample still won't build:

```
# bazel build //examples/android/java/bazel:hello_world
INFO: Found 1 target...
ERROR: /opt/bazel/examples/android/java/bazel/BUILD:20:1: undeclared inclusion(s) in rule '//examples/android/java/bazel:jni':
this rule is missing dependency declarations for the following files included by 'examples/android/java/bazel/jni.cc':
  '/opt/android-ndk/platforms/android-19/arch-arm/usr/include/jni.h'
  '/opt/android-ndk/platforms/android-19/arch-arm/usr/include/sys/cdefs.h'
  '/opt/android-ndk/platforms/android-19/arch-arm/usr/include/sys/cdefs_elf.h'
  '/opt/android-ndk/platforms/android-19/arch-arm/usr/include/android/api-level.h'
  '/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include/stdarg.h'.
Target //examples/android/java/bazel:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.232s, Critical Path: 0.05s
```

I'm not sure why it's looking at android-19 at all since WORKSPACE specified api_level 20. Is arm the issue? Can I force it to use armeabi-v7a somehow or am I not going to be able to build Android on this machine?

**Comment by ahumesky** [comment]
The default cpu for android is armeabi-v7a:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/Constants.java#L38-L39

You can set it to armeabi-v7a explicitly if you'd like with --fat_apk_cpu=armeabi-v7a. What you're seeing in the error are just whatever paths they decided to use for the NDK.

api 19 vs 20 is because for the NDK, 20 is the same as 19 (there is no android-20 directory under platforms). These are translated here:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/android/ndkcrosstools/ApiLevel.java#L50-L67
I thought about having a warning printed here, but I thought it would just be useless noise.

This looks similar to a failure we're seeing on osx:
http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=darwin-x86_64/193/console
but it's passing for linux:
http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/193/console

I would think that this fixes the problem you're seeing, but we must have missed something: https://github.com/bazelbuild/bazel/commit/576819885a67ad1dfecd96641a4522e2817c61ec

**Comment by ahumesky** [comment]
As a workaround, you could try setting hdrs_check to "warn" or "loose" in the cc_library

**Comment by ekuefler** [comment]
Doesn't seem to help, even with `hdrs_check = "warn"` or `hdrs_check = "loose"` on both `cc_library`s under `examples/android/java/bazel` I get the same error message. `--fat_apk_cpu=armeabi-v7a` doesn't seem to have any effect either. I also tried passing `--spawn_strategy=standalone --genrule_strategy=standalone` to check whether it was due to sandboxing, but it didn't make a difference.

Anything else I can try running to get you more information?

**Comment by ahumesky** [comment]
Phil might be able to investigate this further, he's more familiar with sandboxing / hdrs check than I am.

**Comment by lberki** [comment]
My expert opinion is that I have no clue. 

This is surely not a sandbox issue, because we don't sandbox on OS X. My guess is that for some odd reason, gcc dereferences symlinks in the .d file, and thus the paths that Bazel parses out from them are not under the proper external/ directory.

Still digging.

**Comment by lberki** [comment]
It's fixed if I manually replace `toolchainIncludePathTemplate` in `NdkPaths#createToolchainIncludePath` with the non-symlinked directory, so I *think* this is what's happening, which ain't no good.

**Comment by lberki** [comment]
It appears that this is indeed the case: apparently, armeabi-v7a gcc 4.9 on OS X ignores `-no-canonical-prefixes`. Joy.

**Comment by lberki** [comment]
I have a fix! Not on Github yet, but I'm pretty sure it will work.

The issue is that `gcc -xc++ -E -v -` reports different default include paths on Linux and on Mac: on Linux, it returns `$NDK_PATH/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/include` and on OS X, it returns the equivalent source path.

Some include files are found using this path, and it works on Linux, because this path accidentally matches what we put in the `cxx_builtin_include_directory` field of the CROSSTOL file, but it does not on OS X.

The fix is to add matching `-isystem` arguments to the `compiler_flag` field of CROSSTOOL so that the same include files are found by that entry, instead of the one that gcc supplies by default.

I verified and it works, although the change is a bit fiddly.

**Comment by ahumesky** [comment]
ekuefler said though that this was on "Debian on an Ubuntu host machine", so this might not fix the issue? ekuefler, can you confirm if the errors you saw in your 2nd post here are for linux or os x?

**Comment by philwo** [comment]
I've pushed a couple of fixes for the Android example and C++ rules today. Could you please try with Bazel HEAD and see if it works now?

Also, sandboxing is enabled now for C++ builds on Linux (though on Debian I've found that you need to "sudo sysctl kernel.unprivileged_userns_clone=1" to allow non-root to use it and as we found out in the other issue you've filed, Docker containers need to run in privileged mode for sandboxing to work).

With the fixes, the example built correctly on my Ubuntu 14.04 workstation - I'll try tomorrow on a Debian machine, too.

**Comment by ekuefler** [comment]
Yes, my earlier reports were for Linux, and things seem to build OK now (though I had to install lib32stdc++6 and lib32z1 as suggested [here](http://stackoverflow.com/questions/22701405/aapt-ioexception-error-2-no-such-file-or-directory-why-cant-i-build-my-grad) to avoid some extremely unhelpful "file not found" errors from aapt). Thanks - now time for me to go clean up everything that's breaking as a result of C++ sandboxing.

**Comment by ahumesky** [comment]
Great, thanks for your help here
