### ISSUE TITLE
cc_library exposes private headers

### ISSUE THREAD

**Issue by ahippler** [bazelbuild/bazel#6615]
### Description of the problem / feature request:

header files of dependent cc_libraries should only be copied to sandbox if they are added to srcs.

### Feature requests: what underlying problem are you trying to solve with this feature?

i noticed that private header files are copied to sandboxes and producing rebuilds of  of dependen cc_* targets.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD.bazel:
```
cc_library(
    name = "a",
    srcs = ["a.h"],
)
cc_binary(
    name = "b",
    srcs = ["b.c"],
    deps = [":a"],
)
```

a.h:
```
#define FOO 1
```

b.c:
```
#include "a.h"

int main(void) {
    return FOO;
}
```

This should not compile with sandbox execution. Changes in `a.h` should also not trigger a rebuild of `b.c`.

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

release 0.18.1-homebrew

**Comment by ahippler** [comment]
@scentini whats the status of that issue? Why was untriaged removed?

**Comment by scentini** [comment]
Hi there,
The untriaged is removed because this issue now has an assignee.
However, I haven't gotten to it just yet, so there is no progress.

**Comment by jin** [comment]
@scentini could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by scentini** [comment]
Hi, sorry for the delayed response.

I will close this issue as we are aware of it but don't have immediate plans to fix it.
For this we need to implement [modules](https://clang.llvm.org/docs/Modules.html), which is planned somewhere along the road, but we're not there yet.

**Comment by gjasny** [comment]
The problem I face is that a change to a private header of a base library like abseil triggers a complete rebuilt and re-test of the tree.

Why do you need C++ modules to fix the issue? To me it seems that the implicitly formulated dependencies are the problem.

**Comment by hlopko** [comment]
Is that private header included from a public header? Was it a clean build or a incremental build with a running Bazel server?

We use .d files to remove inputs that didn't contribute to the compilation. From that I extrapolate that your private header was actually used during compilation, and it is affecting its outputs. We don't propagate the change further up the graph when action outputs didn't change even though it's inputs have changed. From that I extrapolate that the rebuild of the tree was actually correct thing to do.

If my extrapolations don't correlate with the reality, it might be a bug. Do you have a small repro repo I can play with? Does it only behave this way on mac or also on linux?

**Comment by hlopko** [comment]
Modules are what we use to implement layering checks (that headers included are properly depended on). I thought you care about private headers from the visibility perspective, that you want to prevent others from including the header. After your last comment I see you care about invalidation, so the modules/layering check is irrelevant.

**Comment by jonathanlew** [comment]
I think the issue is that the behaviour of `cc_library` is inconsistent with the specs https://docs.bazel.build/versions/master/be/c-cpp.html#hdrs

Taking a snippet of the given example
```
cc_library(
    name = "bar",
    srcs = [
        "bar.cc",
        "bar-impl.h",
    ],
    hdrs = ["bar.h"],
    deps = [":baz"],
)

cc_library(
    name = "baz",
    srcs = [
        "baz.cc",
        "baz-impl.h",
    ],
    hdrs = ["baz.h"],
)
```
The problem that OP (probably) and I have experienced is that `bar.h`, `bar.cc`, and `bar-impl.h` can all include `baz-impl.h`, even though `baz-impl.h` is in the `srcs` list of `baz`. According to the documentation, only `baz.h` (being a hdr) should be visible to `bar.h`, `bar.cc`, and `bar-impl.h`, and none of the `srcs` should be exposed outside of the `cc_library`

**Comment by hazelnusse** [comment]
Here is another example of this, see the comments in c/c.[ch]pp here:
https://github.com/hazelnusse/bazel_deps_broken_encapsulation

**Comment by hazelnusse** [comment]
@oquenchil I noticed your `implementation_deps` commit recently (2875a25fd0913a4c30d566693bd95c848a67a844). Will this (eventually) address the propagation of implementation details to client libraries? As I understand it, compile flags (includes, defines, and other compile flags) or link flags (there are subtleties here) of a target listed in an `implementation_deps` should not propagate to clients. If you haven't already seen it, there is a pretty nice discussion of how cmake does this [here](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#transitive-usage-requirements). Despite cmake's significant flaws, this is one area I think they got right (over 10 years ago now), and it would be nice if bazel could too.

**Comment by oquenchil** [comment]
That's correct. That's basically what implementation_deps does: includes, defines and headers do not get propagated. `copts` were never propagated though. Linking flags (`linkopts`) and compilation artifacts will still be propagated since linking information in general still needs to make it to the final linked target.

**Comment by hazelnusse** [comment]
@oquenchil does that imply this bug should be closed then? Or is there something more that is not addressed by `implementation_deps`.

Regarding the link flag propagation, I will give bazel master a spin and see how it handles the static vs dynamic link library propagation since that is where some subtleties lie. There is a nice explanation of how library link propagation should work in both the dynamic and static case [here](https://cmake.org/pipermail/cmake/2016-May/063400.html) which I have found quite useful in forming my mental model.

Thank you.

**Comment by oquenchil** [comment]
So it's still behind an experimental flag. I'm not sure it makes sense to close this bug just yet. Please do give it a spin as any feedback is useful.

**Comment by nikhilkalige** [comment]
@oquenchil I tried out `implementation_deps` today, to understand extra rebuilds. It worked as expected. However, I am still getting extra recompilation for private header files, as described in the examples above. I created a similar example with and without `implementation_deps`

- https://github.com/nikhilkalige/bazel-cpp-headers/commit/159b230155fa2b14f05686d482db66db90371502
- https://github.com/nikhilkalige/bazel-cpp-headers/

I am newbie to bazel codebase, so I could entirely wrong. I think private headers from `srcs` attribute are added to include list here
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CcCompilationHelper.java;l=1077;drc=b1d1271db6fdea792db27f403e3c4f38b6db9d9f

which is then used to calculated the action key. Can we not add the private headers to the include list?

**Comment by oquenchil** [comment]
A private header may still be used by one of your public headers. The concept of private headers only makes sense when you are using the layering_check. If you are depending on a target via deps (rather than implementation_deps), its private headers will still be propagated.

**Comment by nikhilkalige** [comment]
In our codebase (CMAKE), we explicitly disallow inclusion of headers in the `srcs` attribute. I was hoping this could be achieved similarly in bazel too. So, all headers from a library that are exposed need to go into the `hdrs` attribute. 

Is there any way to achieve this without layering checks...

**Comment by nikhilkalige** [comment]
For example, if I have library as below...

```c++
## abs.h
class Abstract {
};

## srcs/car.h 
#include "abs.h"
class Car: public Abstract {};

## BUILD
cc_library(name="abs",
  hdrs = [abs.h],
  srcs = [srcs/car.h, ....]
)
```

In this example, why would I want to propagate `srcs/car.h` header file. Yes, I could use `implemenation_deps`, however If my dependent lib exports `Abstract` again, then I would need to use `deps`, but I still do not want the private header file to be exported.

**Comment by oquenchil** [comment]
Unfortunately no way to achieve that without layering check. The only solution I can offer is that you separate the srcs/ headers into its own target that is depended on via implementation_deps from "abs".

**Comment by nikhilkalige** [comment]
@oquenchil I am still trying to understand why would you put a header file in `srcs` if its going to get propagated all the way up the public dependency chain. 

Currently as per you explanation,
If I put `private.h` in `srcs`, then `public.h` in `hdrs` can include it, all the other libs which have this in the `dep`, can also include both the files. Now, can you help me understand why would you `private.h` in srcs, and not put it in `hdrs` itself. It seems like there is no distinction to a header being in `hdrs` or `srcs` (not considering the `implementation_deps`)

I would propose, that header files in `srcs`, be considered private.

**Comment by oquenchil** [comment]
When enabling layering_check, the distinction is made clear. If you are using a header from one of your dependencies and that dependency has the header in hdrs, the layering_check will pass, if it has the header in srcs, the layering_check won't pass. Headers in srcs only make sense in the context of the layering_check. Headers being in `srcs` or `hdrs` is not related to implementation_deps.

**Comment by HappyCerberus** [comment]
> When enabling layering_check, the distinction is made clear. If you are using a header from one of your dependencies and that dependency has the header in hdrs, the layering_check will pass, if it has the header in srcs, the layering_check won't pass.

I just tested it and this statement seems to be incorrect. Adding `--features=layering_check` doesn't prevent the inclusion of private headers (listed in srcs).

**Comment by oquenchil** [comment]
Yes, this requires Clang to work.

**Comment by cameron-martin** [comment]
> A private header may still be used by one of your public headers.

Well it shouldn't, and if it does then I want an error when this is used by a dependent library and the included private header is not available.

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/issues/6615#issuecomment-1742931996 should provide all the answers. `cc_library` now also includes documentation for `layering_check`.
