### ISSUE TITLE
Crash when switching between git_repository and local_repository

### ISSUE THREAD

**Issue by claridge** [bazelbuild/bazel#977]
In 0.2.0, switching a local git_repository to a local_repository, and then back to a git_repository causes Bazel to crash with a "Invalid BUILD file name for package" error. After the crash, "bazel clean --expunge" is needed to return to a working state.

(This is an improvement over 0.1.5, where simply switching a local_repository to a git_repository will trigger the same error.)

**Comment by bsilver8192** [comment]
A bit more debugging info: the repository gets changed from a git repository to a symlink to the local directory as expected, but then changing it back to a git repository fails. Shutting down the server in between makes it work, but once it fails, restarting the server does not fix it.

**Comment by damienmg** [comment]
Can you try with head, I fixed a similar bug today :)

**Comment by damienmg** [comment]
26f7f4849d4f56d23d21111ee17248ab64065009 is the change for reference

**Comment by bsilver8192** [comment]
I was already trying that :). That commit changes the behavior, but it's still wrong. The behavior before that commit was already different than 0.2.0. git -> local -> git was building without any errors but still resulted in the repository pointing to the local one. Switching back to the local one again at that point resulted in the same error. With that commit, it seems perfectly happy to build with the repository pointing at a local directory instead of being a git repository through any combination of switching repository types, shutting down, and building I can think of.

**Comment by damienmg** [comment]
You mean without `bazel clean --expunge`?

**Comment by damienmg** [comment]
/cc @kchodorow 

I don't think I will have time to have a look at what happens soon but that's definitely likely to happen :)

**Comment by bsilver8192** [comment]
Correct: current master happily builds with the repository as a symlink pointing to the local directory before and after switching to git_repository without a `bazel clean --expunge` or `bazel shutdown` or anything.

**Comment by damienmg** [comment]
But it was already the case earlier before 0.2, right?

**Comment by bsilver8192** [comment]
No, it was different before 0.2... Here's an overall summary of the behavior I've seen:

<table><tr><th>version</th><th>works</th><th>doesn't work</th></tr>
<tr><td>Older (before 0.2)</td><td></td><td>local -> git</td></tr>
<tr><td>0.2.0</td><td><ul><li>local -> git</li><li>local -> git, shutdown, -> local</li></td><td>local -> git -> local</td></tr>
<tr><td>before 26f7f48</td><td>git -> local</td><td><ul><li>git -> local -> git (built, but with the local_repository still like the next one)</li><li>git -> local -> git -> local</li></ul></td></tr>
<tr><td>after 26f7f48</td><td>Any combination I tried built</td><td><ul><li>Even after building successfully with a git_repository, the external folder still had a symlink instead of a git repository in a folder</li><li>Even with the local_repository pointing to a folder without a .git folder</li></ul></td></tr>
</table>

**Comment by damienmg** [comment]
Ok thanks for the summary!
